@prefix = http://localhost:4002/api/sites/netease

###! news
GET {{prefix}}/news/comment
###
GET {{prefix}}/news/rank
###
GET {{prefix}}/news/search
###
GET {{prefix}}/news/video
###
GET {{prefix}}/news/topic