@host = http://localhost:4002

### test
### redis
GET {{host}}/api/query?q=juejin/mix
###
GET {{host}}/api/del?q=tencent-news/hot











### toutiao
GET {{host}}/api/sites/toutiao/hot




### 澎湃
### 热榜
GET {{host}}/api/sites/pengpai/hot
### 频道
GET {{host}}/api/sites/pengpai/channels/25950
### 节点
GET {{host}}/api/sites/pengpai/nodes/25462

### 梨视频 热榜
###
GET {{host}}/api/sites/pearvideo/rank
###

### 搜狗
GET {{host}}/api/sites/sogou
###

### acfun


### shadiaonews
GET {{host}}/api/sites/shadiaonews
###


###



### 
### tencent news
GET {{host}}/api/sites/tencent-news/hot
### 
