@prefix = http://localhost:4002/api/sites/xueqiu

### xueqiu
GET {{prefix}}/cookie
###
#TODO: update
GET {{prefix}}/livenews
###
GET {{prefix}}/notice
###
GET {{prefix}}/news
###
GET {{prefix}}/hotstock
###