@news = http://localhost:4002/api/sites/tencent/news
@weread = http://localhost:4002/api/sites/tencent/weread

###? News
GET {{news}}/question
###
GET {{news}}/rank

###? Weread
GET {{weread}}/