@prefix = http://localhost:4002/api/sites/jiandan

### jiandan
GET {{prefix}}/4h
###
GET {{prefix}}/3d
###
GET {{prefix}}/7h
###
GET {{prefix}}/ooxx
###
GET {{prefix}}/top
###
GET {{prefix}}/comments
###
GET {{prefix}}/tucao