@prefix = http://localhost:4002/api/sites/hupu
###
GET {{prefix}}/plate?tab=sports
###
GET  {{prefix}}/plate?tab=gambia
###
GET  {{prefix}}/plate?tab=ent
###
GET {{prefix}}/plate?tab=lol
###
GET {{prefix}}/plate?tab=game
###
GET {{prefix}}/plate?tab=gear
###
GET {{prefix}}/plate?tab=soccer
###
GET {{prefix}}/plate?tab=digital