@prefix = http://localhost:4002/api/sites/weibo

###
GET {{prefix}}/cookie

###
POST {{prefix}}/verify
Content-Type: application/json

{
  "phone": "15697544151"
}

###
POST {{prefix}}/login
Content-Type: application/json

{
  "phone": "15697544151",
  "smscode": "724591",
  "getuser": 0,
  "getcookie": 1,
  "getoauth": 1
}


### weibo
GET {{prefix}}/hotsearch
###
GET {{prefix}}/socialevent
###
GET {{prefix}}/entrank
###
GET {{prefix}}/topicband
